# Generated by Django 5.2.7 on 2025-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.TextField(default='', help_text='breakfast/lunch/dinner'),
        ),
    ]
