# Generated by Django 5.2.7 on 2025-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_user_followers_user_friends_friendrequest'),
        ('recipes', '0006_recipe_created_at_recipe_updated_at_and_more'),
    ]

    operations = [
    ]
