# Generated by Django 5.2.7 on 2025-12-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_user_is_private_followrequest_delete_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlannedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=20)),
                ('planned_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='recipes.plannedday')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='recipes.recipe')),
            ],
            options={
                'unique_together': {('planned_day', 'meal_type', 'recipe')},
            },
        ),
    ]
