# Generated by Django 5.2.7 on 2025-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_plannedday_plannedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image from your device', null=True, upload_to='recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide an image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step cooking instructions'),
        ),
    ]
