# Generated by Django 5.2.7 on 2025-12-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, help_text='Last time this recipe was viewed', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this recipe has been viewed'),
        ),
    ]
