# Generated by Django 5.2.7 on 2025-12-24 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recipes', '0012_recipe_last_viewed_at_recipe_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden by moderator or auto-hidden due to reports'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden by moderator or auto-hidden due to reports'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_received', 'Report Received'), ('report_resolved', 'Report Resolved'), ('content_removed', 'Content Removed'), ('content_hidden', 'Content Hidden'), ('content_restored', 'Content Restored'), ('warning_issued', 'Warning Issued'), ('follow_request', 'Follow Request'), ('comment_reply', 'Comment Reply'), ('recipe_rated', 'Recipe Rated'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='recipes_not_recipie_567f13_idx'), models.Index(fields=['recipient', 'is_read'], name='recipes_not_recipie_24d98b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam or Advertising'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('offensive', 'Offensive Language'), ('copyright', 'Copyright Violation'), ('misinformation', 'False or Misleading Information'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text="Please provide details about why you're reporting this content")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_action', models.CharField(choices=[('none', 'No Action Taken'), ('dismissed', 'Report Dismissed'), ('hidden', 'Content Hidden'), ('deleted', 'Content Deleted'), ('warned', 'Author Warned'), ('banned', 'Author Banned')], default='none', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Admin notes about the decision')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('reported_by', 'content_type', 'object_id')},
            },
        ),
    ]
